### ISSUE TITLE
State updates and auto-rerender of feed when creating or deleting a review

### ISSUE THREAD

**Issue by thedrewery** [thedrewery/koo-koo-drew#27]
@jasonbarry Before I get any deeper on the edit review functionality, I wanted to see about the best way to update state for the displayed reviews so they automatically re-render when a review is added/deleted. Right now the delete functionality is written in the Review component, the create functionality is written in the NewReview component, and the api calls to get and display the correct reviews for the user are done in the ReviewsDisplay component.

**Comment by jasonbarry** [comment]
I'd recommend pulling your fetches up higher so that they are on the App or page level rather than leaf component level. Maintain the state higher up, and pass the data as props to the components that render that data. 

I'd also recommend defining your fetches in a utility file that you can import at the top level. That way you can have all your API methods in one place, share headers, etc.
